download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/ansible-controller-4.6.2.tar.gz
format_version: 1.0.0
name: controller
namespace: ansible
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2024-10-24T07:40:15.074088Z'
  signature: '-----BEGIN PGP SIGNATURE-----

    Version: GnuPG v1


    iQIcBAABCAAGBQJnGfnMAAoJEOGkvXCKgoqtpXoQAKonc0pq9ySH4iTgmZKkgIr5

    ES0nxR4L/KX71yhb8ykNR1kK3AmFH+pcB9yIkQj4HeT1SXPLNRhlG0K/m7/MNMGp

    KzLU7zUPf83f7uJIsGGUfXaSzbbBe1R7aUp8j0kbIrWv89vUljL7bBzJ1FKCifkz

    LQgPa6kywF+c+NvL2dJaLWPGAubcNvnqH4lhVx4cfnucOKoNS1DgwTD3Q4/RGs4C

    dS380qlyX8reH/WFuW9/Lz1US6jHrpI2gGR/02Vu0FaEGLdAEMa8CAC13MQZ5DVF

    X+wdh66WLBWmF91Z/YSEtvvypkGE1z/7qaKd+y9g78+Cn9/Sz4FKO9gTW5bpEojV

    KTJi/v3cFCPmFJJIDZiBryi6s/w2hZCeNNwdwYMBlg7JFWbF3KsweeZGERcs74ZH

    BV4rc0Ggau6iiE0lMMi6WoAVA0w9ah9lcGafzHi9uoGQHUfdxiKDFSqwLKI2K/g/

    8TmQrcuYtKnTcX8c/C4iqO5HXf9Vd785R0Da7e9M5nN0laJSEahGFQCcyKIol4cx

    YQJgOZGFCY8no7y8isRQFRLVArbAVQlG6VIIFXrwTg/ZpXhZVRr2kdAEh2HEFw7K

    iY8Ykn1CDfMRIKXZzAmsOsb2Ij1OU6p0jbs9VwY0I0Zxto8QbCR8vs0UvVfqDB+7

    RlHgweqfhGQvVRTFfiz1

    =6geL

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 4.6.2
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/ansible/controller/versions/4.6.2/
