# SPDX-License-Identifier: MIT
---
galaxy_info:
  author: Michal Sekletar <msekleta@redhat.com>
  description: Deploy and control systemd units
  galaxy_tags:
    - system
    - systemd
    - service
    - rhel
    - fedora
    - centos
  company: Red Hat, Inc.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"

allow_duplicates: true
