---
- name: Gather host & pkg facts
  hosts: all 
  become: true 
  gather_facts: true 
  tasks:

  - name: Gather host facts 
    ansible.builtin.setup:

  - name: Gather package facts 
    ansible.builtin.package_facts:

  - name: Print host facts 
    ansible.builtin.debug:
      var: ansible_facts 

  - name: Print package facts 
    ansible.builtin.debug:
      var: ansible_facts.packages

  - name: Demo leveraging facts 
