---
- name: test ansible.controller.inventory
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Add inventory
      ansible.controller.inventory:
        #controller_host: "containerizedaap.beaverdam.com:8443"
        controller_host: "controller.beaverdam.com"
        #controller_username: "admin"
        #controller_password: "redhat"
        name: "Test Inventory"
        description: "Our Test Cloud Servers"
        organization: "Default"
        state: present
        validate_certs: false
