---
- name: test ansible.controller.inventory
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Add inventory
      ansible.controller.inventory:
        controller_host: "containerizedaap.beaverdam.com:8443"
        name: "Test Inventory"
        description: "Our Test Cloud Servers"
        organization: 1
        state: present
        validate_certs: false
