---
- name: test ansible.controller.inventory
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Add inventory
      ansible.controller.inventory:
        controller_host: "controller.beaverdam.com"
        name: "Test Inventory"
        description: "Our Test Cloud Servers"
        organization: "Default"
        state: present
        validate_certs: false

- name: test ansible.controller.host
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Add host
      ansible.controller.host:
        name: localhost
        description: "Local Host Group"
        inventory: "Test Inventory"
        state: present
        variables:
          example_var: 123
