---
- name: Provision host in satellite
  hosts: localhost 
  gather_facts: false 
  tasks:

  - name: "Create a host with build context"
    redhat.satellite.host:
      username: "admin"
      password: "redhat"
      server_url: "https://sat6.tamlab.rdu2.redhat.com"
      name: "cbeaverdemo2.tamlab.rdu2.redhat.com"
      state: present
      organization: tamlab
      location: RDU   
      compute_resource: VMWare
      compute_profile: cbeaver_VMWare
      content_source: sat6.tamlab.rdu2.redhat.com
      #mac: 00:50:56:af:5f:99
      architecture: x86_64
      operatingsystem: RedHat 9.3 
      validate_certs: false 
      build: true 
      provision_method: image
      compute_attributes:
        network: TAMLAB_193 
      image: rhel9_blank

# instance cbeaverdemo2.tamlab.rdu2.********.com: Unknown Network ID: \n "], 