---
# defaults file for infra.aap_utilities.aap_restore

############################################################
#               AAP Restore Vars                           #
############################################################

# Restore location for AAP restore
aap_restore_file: "automation-platform-backup-latest.tar.gz"
aap_restore_location: "{{ aap_setup_working_dir }}/{{ aap_restore_file }}"
...
