---
name: Changelog

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main
