---
# tasks file for aap_restore

#
# -----------------------------------------------------------------------------
# Prepare for AAP work
# -----------------------------------------------------------------------------
#

- name: Include restore tasks
  ansible.builtin.include_tasks: restore.yml
  tags:
    - restore
...
